export interface ITemperatuurPerPeriode {
  jaar: number,
  maand: number,
  dag: number,
  uur: number,
  avg_temp_indoor: number,
  min_temp_indoor: number,
  max_temp_indoor: number,
  avg_temp_1: number,
  min_temp_1: number,
  max_temp_1: number,
  avg_temp_2: number,
  min_temp_2: number,
  max_temp_2: number,
  avg_temp_3: number,
  min_temp_3: number,
  max_temp_3: number,
  avg_temp_4: number,
  min_temp_4: number,
  max_temp_4: number
}
